name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      platform:
        required: true
        type: string
      pio_env:
        required: true
        type: string
      meshtastic_firmware_ref:
        required: true
        type: string

permissions: read-all

jobs:
  pio-build:
    name: build-${{ inputs.platform }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        name: Checkout Meshtastic firmware
        with:
          submodules: recursive
          repository: meshtastic/firmware
          ref: ${{ inputs.meshtastic_firmware_ref }}

      - name: Build ${{ inputs.platform }}
        id: build
        uses: meshtastic/gh-action-firmware@main
        with:
          pio_platform: ${{ inputs.platform }}
          pio_env: ${{ inputs.pio_env }}
          pio_target: build

      - name: Store binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ inputs.platform }}-${{ inputs.pio_env }}-${{ inputs.version }}.zip
          overwrite: true
          path: |
            release/*.bin
            release/*.elf
            release/*.uf2
            release/*.hex
            release/*-ota.zip
